import localeinfo
import uiscriptlocale

ROOT_PATH="new/login/"
IMG_PATHBG = "new/login/animation/bg/"
IMG_PATHLOGO = "new/login/animation/logo/"

ID_LIMIT_COUNT=17
PW_LIMIT_COUNT=16

SCALE_X=float(SCREEN_WIDTH)/1920.0
SCALE_Y=float(SCREEN_HEIGHT)/1080.0

if SCREEN_HEIGHT==600:
	LOGO_SCALE_X=0.65
	LOGO_SCALE_Y=0.65
	LOGO_HEIGHT=(SCREEN_HEIGHT-226)/2-176
else:
	LOGO_SCALE_X=1.0
	LOGO_SCALE_Y=1.0
	LOGO_HEIGHT=(SCREEN_HEIGHT-226)/2-256

if SCREEN_WIDTH<=800:
	RENDER1_SCALE_X=SCALE_X/2.4
	RENDER1_SCALE_Y=SCALE_Y/2.4

	RENDER2_SCALE_X=SCALE_X/2
	RENDER2_SCALE_Y=SCALE_Y/2
elif SCREEN_WIDTH<=1024:
	RENDER1_SCALE_X=SCALE_X/1.6
	RENDER1_SCALE_Y=SCALE_Y/1.6

	RENDER2_SCALE_X=SCALE_X/1.6
	RENDER2_SCALE_Y=SCALE_Y/1.6
else:
	RENDER1_SCALE_X=SCALE_X
	RENDER1_SCALE_Y=SCALE_Y

	RENDER2_SCALE_X=SCALE_X
	RENDER2_SCALE_Y=SCALE_Y

window={
	"name":"LoginWindowUI",
	"sytle":("movable",),
	"x":0,
	"y":0,
	"width":SCREEN_WIDTH,
	"height":SCREEN_HEIGHT,
	"children":
	(
		{
			"name":"BackgroundUI",
			"type":"ani_image",
			"x":0,
			"y":0,
			"image":ROOT_PATH+"bg.jpg",
			"x_scale":float(SCREEN_WIDTH) / 1920.0,
			"y_scale":float(SCREEN_HEIGHT) / 1080.0,
			"delay": 2,
			"images" : (
				IMG_PATHBG + "bg_00000.dds",
				IMG_PATHBG + "bg_00001.dds",
				IMG_PATHBG + "bg_00002.dds",
				IMG_PATHBG + "bg_00003.dds",
				IMG_PATHBG + "bg_00004.dds",
				IMG_PATHBG + "bg_00005.dds",
				IMG_PATHBG + "bg_00006.dds",
				IMG_PATHBG + "bg_00007.dds",
				IMG_PATHBG + "bg_00008.dds",
				IMG_PATHBG + "bg_00009.dds",
				IMG_PATHBG + "bg_00010.dds",
				IMG_PATHBG + "bg_00011.dds",
				IMG_PATHBG + "bg_00012.dds",
				IMG_PATHBG + "bg_00013.dds",
				IMG_PATHBG + "bg_00014.dds",
				IMG_PATHBG + "bg_00015.dds",
				IMG_PATHBG + "bg_00016.dds",
				IMG_PATHBG + "bg_00017.dds",
				IMG_PATHBG + "bg_00018.dds",
				IMG_PATHBG + "bg_00019.dds",
				IMG_PATHBG + "bg_00020.dds",
				IMG_PATHBG + "bg_00021.dds",
				IMG_PATHBG + "bg_00022.dds",
				IMG_PATHBG + "bg_00023.dds",
				IMG_PATHBG + "bg_00024.dds",
				IMG_PATHBG + "bg_00025.dds",
				IMG_PATHBG + "bg_00026.dds",
				IMG_PATHBG + "bg_00027.dds",
				IMG_PATHBG + "bg_00028.dds",
				IMG_PATHBG + "bg_00029.dds",
				IMG_PATHBG + "bg_00030.dds",
				IMG_PATHBG + "bg_00031.dds",
				IMG_PATHBG + "bg_00032.dds",
				IMG_PATHBG + "bg_00033.dds",
				IMG_PATHBG + "bg_00034.dds",
				IMG_PATHBG + "bg_00035.dds",
				IMG_PATHBG + "bg_00036.dds",
				IMG_PATHBG + "bg_00037.dds",
				IMG_PATHBG + "bg_00038.dds",
				IMG_PATHBG + "bg_00039.dds",
				IMG_PATHBG + "bg_00040.dds",
				IMG_PATHBG + "bg_00041.dds",
				IMG_PATHBG + "bg_00042.dds",
				IMG_PATHBG + "bg_00043.dds",
				IMG_PATHBG + "bg_00044.dds",
				IMG_PATHBG + "bg_00045.dds",
				IMG_PATHBG + "bg_00046.dds",
				IMG_PATHBG + "bg_00047.dds",
				IMG_PATHBG + "bg_00048.dds",
				IMG_PATHBG + "bg_00049.dds",
				IMG_PATHBG + "bg_00050.dds",
				IMG_PATHBG + "bg_00051.dds",
				IMG_PATHBG + "bg_00052.dds",
				IMG_PATHBG + "bg_00053.dds",
				IMG_PATHBG + "bg_00054.dds",
				IMG_PATHBG + "bg_00055.dds",
				IMG_PATHBG + "bg_00056.dds",
				IMG_PATHBG + "bg_00057.dds",
				IMG_PATHBG + "bg_00058.dds",
				IMG_PATHBG + "bg_00059.dds",
				IMG_PATHBG + "bg_00060.dds",
				IMG_PATHBG + "bg_00061.dds",
				IMG_PATHBG + "bg_00062.dds",
				IMG_PATHBG + "bg_00063.dds",
				IMG_PATHBG + "bg_00064.dds",
				IMG_PATHBG + "bg_00065.dds",
				IMG_PATHBG + "bg_00066.dds",
				IMG_PATHBG + "bg_00067.dds",
				IMG_PATHBG + "bg_00068.dds",
				IMG_PATHBG + "bg_00069.dds",
				IMG_PATHBG + "bg_00070.dds",
				IMG_PATHBG + "bg_00071.dds",
				IMG_PATHBG + "bg_00072.dds",
				IMG_PATHBG + "bg_00073.dds",
				IMG_PATHBG + "bg_00074.dds",
				IMG_PATHBG + "bg_00075.dds",
				IMG_PATHBG + "bg_00076.dds",
				IMG_PATHBG + "bg_00077.dds",
				IMG_PATHBG + "bg_00078.dds",
				IMG_PATHBG + "bg_00079.dds",
				IMG_PATHBG + "bg_00080.dds",
				IMG_PATHBG + "bg_00081.dds",
				IMG_PATHBG + "bg_00082.dds",
				IMG_PATHBG + "bg_00083.dds",
				IMG_PATHBG + "bg_00084.dds",
				IMG_PATHBG + "bg_00085.dds",
				IMG_PATHBG + "bg_00086.dds",
				IMG_PATHBG + "bg_00087.dds",
				IMG_PATHBG + "bg_00088.dds",
				IMG_PATHBG + "bg_00089.dds",
				IMG_PATHBG + "bg_00090.dds",
				IMG_PATHBG + "bg_00091.dds",
				IMG_PATHBG + "bg_00092.dds",
				IMG_PATHBG + "bg_00093.dds",
				IMG_PATHBG + "bg_00094.dds",
				IMG_PATHBG + "bg_00095.dds",
			),

		},
		{
			"name":"Render1UI",
			"type":"expanded_image",
			# "image":ROOT_PATH+"render1.tga",
			"x_scale":RENDER1_SCALE_X,
			"y_scale":RENDER1_SCALE_Y,
			"vertical_align":"bottom",
			"horizontal_align":"left",
			"x":0,
			"y":46+(RENDER1_SCALE_Y * 696),
		},
		{
			"name":"Render2UI",
			"type":"expanded_image",
			# "image":ROOT_PATH+"render2.tga",
			"x_scale":RENDER2_SCALE_X,
			"y_scale":RENDER2_SCALE_Y,
			"vertical_align":"bottom",
			"horizontal_align":"right",
			"x":RENDER2_SCALE_X*630,
			"y":46+(RENDER2_SCALE_Y * 800),
		},
		{
			"name":"LineUI",
			"type":"expanded_image",
			"image":ROOT_PATH+"line.tga",
			"x_scale":SCALE_X,
			"y_scale":1.0,
			"vertical_align":"bottom",
			"x":0,
			"y":49,
			"children":
			(
				{
					"name":"WebsiteButtonUI",
					"type":"button",
					"default_image":"new/login/website_icon_normal.png",
					"over_image":"new/login/website_icon_down.png",
					"down_image":"new/login/website_icon_over.png",
					"disable_image":"new/login/website_icon_over.png",
					"x":((SCREEN_WIDTH-34)/2)-128,
					"y":8,
				},
				{
					"name":"DiscordButtonUI",
					"type":"button",
					"default_image":"new/login/discord_button_normal.sub",
					"over_image":"new/login/discord_button_down.sub",
					"down_image":"new/login/discord_button_over.sub",
					"disable_image":"new/login/discord_button_over.sub",
					"x":((SCREEN_WIDTH-34)/2)+128,
					"y":8,
				},
			),
		},
		{
			"name":"MenuUI",
			"type":"window",
			"width":680,
			"height":480,
			"x":(SCREEN_WIDTH-680)/2,
			"y":(SCREEN_HEIGHT-500)/2+96,
			"children":
			(
				{
					"name":"MenuLeftUI",
					"type":"image",
					"image":ROOT_PATH+"menu_left_empty.sub",
					"x":0,
					"y":0,
					"horizontal_align":"left",
					"children":
					(
						{
							"name":"MenuLeftTitleBarUI",
							"type":"window",
							"width":200,
							"height":18,
							"horizontal_align":"center",
							"x":0,
							"y":11,
							"children":
							(
								{
									"name":"MenuLeftTitleUI",
									"type":"text",
									"text":uiscriptlocale.LOGINWINDOW_LOGIN_PANEL,
									"fontname":"Tahoma:13b",
									"color":0x3dffffc1,
									"all_align":1,
									"x":0,
									"y":0,
								},
							),
						},
						{
							"name":"UsernameInputUI",
							"type":"image",
							"horizontal_align":"center",
							"image":ROOT_PATH+"input_username.sub",
							"x":0,
							"y":58,
							"children":
							(
								{
									"name":"UsernameEditLineUI",
									"type":"editline",
									"width":163,
									"height":20,
									"color":0xffffffff,
									"x":40,
									"y":10,
									"input_limit":ID_LIMIT_COUNT,
								},
								{
									"name":"UsernameWelcomeUI",
									"type":"button",
									"width":163,
									"height":20,
									"text":uiscriptlocale.UI_USERNAME,
									"text_color":0xffffffff,
									"text_x":0,
									"text_y":5,
									"x":40,
									"y":10,
								},
							),
						},
						{
							"name":"PasswordInputUI",
							"type":"image",
							"horizontal_align":"center",
							"image":ROOT_PATH+"input_password.sub",
							"x":0,
							"y":115,
							"children":
							(
								{
									"name":"PasswordEditLineUI",
									"type":"editline",
									"width":163,
									"height":20,
									"color":0xffffffff,
									"x":40,
									"y":10,
									"input_limit":PW_LIMIT_COUNT,
									"secret_flag":1,
								},
								{
									"name":"PasswordWelcomeUI",
									"type":"button",
									"width":163,
									"height":20,
									"text":uiscriptlocale.UI_PASSWORD,
									"text_color":0xffffffff,
									"text_x":0,
									"text_y":5,
									"x":40,
									"y":10,
								},
							),
						},
						{
							"name":"ChannelTextUI",
							"type":"button",
							"x":0,
							"y":172,
							"text":"",
							"color":0xffffffff,
							"horizontal_align":"center",
						},
						{
							"name":"LoginButtonUI",
							"type":"button",
							"x":0,
							"y":196,
							"horizontal_align":"center",
							"default_image":ROOT_PATH+"login_button_normal.sub",
							"over_image":ROOT_PATH+"login_button_over.sub",
							"down_image":ROOT_PATH+"login_button_down.sub",
							"disable_image":ROOT_PATH+"login_button_down.sub",
							"text":uiscriptlocale.LOGINWINDOW_LOGIN,
							"text_color":0xffffffff,
						},
						{
							"name":"RegisterTextUI",
							"type":"button",
							"x":0,
							"y":258,
							"horizontal_align":"center",
							"width":200,
							"height":16,
							"text":uiscriptlocale.LOGINWINDOW_NOT_REGISTERED,
						},
						{
							"name":"ForgotTextUI",
							"type":"button",
							"x":0,
							"y":278,
							"horizontal_align":"center",
							"width":200,
							"height":16,
							"text":uiscriptlocale.LOGINWINDOW_FORGOT_DETAILS,
						},
						{
							"name":"ExitTextUI",
							"type":"button",
							"x":0,
							"y":310,
							"horizontal_align":"center",
							"width":80,
							"height":20,
							"text":uiscriptlocale.LOGINWINDOW_EXIT,
						},
					),
				},
				{
					"name":"MenuCenterUI",
					"type":"window",
					"width":71,
					"height":286,
					"horizontal_align":"center",
					"x":0,
					"y":38,
					"children":
					(
						{
							"name":"Ch1ButtonUI",
							"type":"button",
							"x":0,
							"y":0,
							"default_image":"new/login/ch_button_normal.sub",
							"over_image":"new/login/ch_button_over.sub",
							"down_image":"new/login/ch_button_over.sub",
							"disable_image":"new/login/ch_button_down.sub",
							"text":"",
							"text_color":0xffffffff,
						},
						{
							"name":"Ch2ButtonUI",
							"type":"button",
							"x":0,
							"y":67+6,
							"default_image":"new/login/ch_button_normal.sub",
							"over_image":"new/login/ch_button_over.sub",
							"down_image":"new/login/ch_button_over.sub",
							"disable_image":"new/login/ch_button_down.sub",
							"text":"",
							"text_color":0xffffffff,
						},
						{
							"name":"Ch3ButtonUI",
							"type":"button",
							"x":0,
							"y":(67*2)+(6*2),
							"default_image":"new/login/ch_button_normal.sub",
							"over_image":"new/login/ch_button_over.sub",
							"down_image":"new/login/ch_button_over.sub",
							"disable_image":"new/login/ch_button_down.sub",
							"text":"",
							"text_color":0xffffffff,
						},
						{
							"name":"Ch4ButtonUI",
							"type":"button",
							"x":0,
							"y":(67*3)+(6*3),
							"default_image":"new/login/ch_button_normal.sub",
							"over_image":"new/login/ch_button_over.sub",
							"down_image":"new/login/ch_button_over.sub",
							"disable_image":"new/login/ch_button_down.sub",
							"text":"",
							"text_color":0xffffffff,
						},
					),
				},
				{
					"name":"MenuRightUI",
					"type":"image",
					"image":ROOT_PATH+"menu_right_empty.sub",
					"x":291,
					"y":0,
					"horizontal_align":"right",
					"children":
					(
						{
							"name":"MenuRightTitleBarUI",
							"type":"window",
							"width":200,
							"height":18,
							"horizontal_align":"center",
							"x":0,
							"y":11,
							"children":
							(
								{
									"name":"MenuRightTitleUI",
									"type":"text",
									"text":uiscriptlocale.LOGINWINDOW_SAVE_ACCOUNT,
									"fontname":"Tahoma:13b",
									"color":0x3dffffc1,
									"all_align":1,
									"x":0,
									"y":0,
								},
							),
						},
						{
							"name":"Account1SlotUI",
							"type":"image",
							"image":ROOT_PATH+"account_bg.sub",
							"horizontal_align":"center",
							"x":0,
							"y":58,
							"children":
							(
								{
									"name":"Account0TextUI",
									"type":"text",
									"text":"",
									"color":0xffffffff,
									"x":12,
									"y":14,
								},
								{
									"name":"Account0SaveUI",
									"type":"button",
									"default_image":ROOT_PATH+"save_account_normal.sub",
									"over_image":ROOT_PATH+"save_account_over.sub",
									"down_image":ROOT_PATH+"save_account_down.sub",
									"horizontal_align":"right",
									"vertical_align":"center",
									"x":24,
									"y":0,
								},
								{
									"name":"Account0DeleteUI",
									"type":"button",
									"default_image":ROOT_PATH+"delete_account_normal.sub",
									"over_image":ROOT_PATH+"delete_account_over.sub",
									"down_image":ROOT_PATH+"delete_account_down.sub",
									"horizontal_align":"right",
									"vertical_align":"center",
									"x":40,
									"y":0,
								},
							),
						},
						{
							"name":"Account2SlotUI",
							"type":"image",
							"image":ROOT_PATH+"account_bg.sub",
							"horizontal_align":"center",
							"x":0,
							"y":97,
							"children":
							(
								{
									"name":"Account1TextUI",
									"type":"text",
									"text":"",
									"color":0xffffffff,
									"x":12,
									"y":14,
								},
								{
									"name":"Account1SaveUI",
									"type":"button",
									"default_image":ROOT_PATH+"save_account_normal.sub",
									"over_image":ROOT_PATH+"save_account_over.sub",
									"down_image":ROOT_PATH+"save_account_down.sub",
									"horizontal_align":"right",
									"vertical_align":"center",
									"x":24,
									"y":0,
								},
								{
									"name":"Account1DeleteUI",
									"type":"button",
									"default_image":ROOT_PATH+"delete_account_normal.sub",
									"over_image":ROOT_PATH+"delete_account_over.sub",
									"down_image":ROOT_PATH+"delete_account_down.sub",
									"horizontal_align":"right",
									"vertical_align":"center",
									"x":40,
									"y":0,
								},
							),
						},
						{
							"name":"Account3SlotUI",
							"type":"image",
							"image":ROOT_PATH+"account_bg.sub",
							"horizontal_align":"center",
							"x":0,
							"y":136,
							"children":
							(
								{
									"name":"Account2TextUI",
									"type":"text",
									"text":"",
									"color":0xffffffff,
									"x":12,
									"y":14,
								},
								{
									"name":"Account2SaveUI",
									"type":"button",
									"default_image":ROOT_PATH+"save_account_normal.sub",
									"over_image":ROOT_PATH+"save_account_over.sub",
									"down_image":ROOT_PATH+"save_account_down.sub",
									"horizontal_align":"right",
									"vertical_align":"center",
									"x":24,
									"y":0,
								},
								{
									"name":"Account2DeleteUI",
									"type":"button",
									"default_image":ROOT_PATH+"delete_account_normal.sub",
									"over_image":ROOT_PATH+"delete_account_over.sub",
									"down_image":ROOT_PATH+"delete_account_down.sub",
									"horizontal_align":"right",
									"vertical_align":"center",
									"x":40,
									"y":0,
								},
							),
						},
						{
							"name":"Account4SlotUI",
							"type":"image",
							"image":ROOT_PATH+"account_bg.sub",
							"horizontal_align":"center",
							"x":0,
							"y":175,
							"children":
							(
								{
									"name":"Account3TextUI",
									"type":"text",
									"text":"",
									"color":0xffffffff,
									"x":12,
									"y":14,
								},
								{
									"name":"Account3SaveUI",
									"type":"button",
									"default_image":ROOT_PATH+"save_account_normal.sub",
									"over_image":ROOT_PATH+"save_account_over.sub",
									"down_image":ROOT_PATH+"save_account_down.sub",
									"horizontal_align":"right",
									"vertical_align":"center",
									"x":24,
									"y":0,
								},
								{
									"name":"Account3DeleteUI",
									"type":"button",
									"default_image":ROOT_PATH+"delete_account_normal.sub",
									"over_image":ROOT_PATH+"delete_account_over.sub",
									"down_image":ROOT_PATH+"delete_account_down.sub",
									"horizontal_align":"right",
									"vertical_align":"center",
									"x":40,
									"y":0,
								},
							),
						},
						{
							"name":"Account5SlotUI",
							"type":"image",
							"image":ROOT_PATH+"account_bg.sub",
							"horizontal_align":"center",
							"x":0,
							"y":214,
							"children":
							(
								{
									"name":"Account4TextUI",
									"type":"text",
									"text":"",
									"color":0xffffffff,
									"x":12,
									"y":14,
								},
								{
									"name":"Account4SaveUI",
									"type":"button",
									"default_image":ROOT_PATH+"save_account_normal.sub",
									"over_image":ROOT_PATH+"save_account_over.sub",
									"down_image":ROOT_PATH+"save_account_down.sub",
									"horizontal_align":"right",
									"vertical_align":"center",
									"x":24,
									"y":0,
								},
								{
									"name":"Account4DeleteUI",
									"type":"button",
									"default_image":ROOT_PATH+"delete_account_normal.sub",
									"over_image":ROOT_PATH+"delete_account_over.sub",
									"down_image":ROOT_PATH+"delete_account_down.sub",
									"horizontal_align":"right",
									"vertical_align":"center",
									"x":40,
									"y":0,
								},
							),
						},
						{
							"name":"Account6SlotUI",
							"type":"image",
							"image":ROOT_PATH+"account_bg.sub",
							"horizontal_align":"center",
							"x":0,
							"y":253,
							"children":
							(
								{
									"name":"Account5TextUI",
									"type":"text",
									"text":"",
									"color":0xffffffff,
									"x":12,
									"y":14,
								},
								{
									"name":"Account5SaveUI",
									"type":"button",
									"default_image":ROOT_PATH+"save_account_normal.sub",
									"over_image":ROOT_PATH+"save_account_over.sub",
									"down_image":ROOT_PATH+"save_account_down.sub",
									"horizontal_align":"right",
									"vertical_align":"center",
									"x":24,
									"y":0,
								},
								{
									"name":"Account5DeleteUI",
									"type":"button",
									"default_image":ROOT_PATH+"delete_account_normal.sub",
									"over_image":ROOT_PATH+"delete_account_over.sub",
									"down_image":ROOT_PATH+"delete_account_down.sub",
									"horizontal_align":"right",
									"vertical_align":"center",
									"x":40,
									"y":0,
								},
							),
						},
					),
				},
				{
					"name":"menu_center_bottom2_ui",
					"type":"window",
					"x":0,
					"y":146,
					"width":180,
					"height":100,
					"horizontal_align":"center",
					"vertical_align":"bottom",
					"children":
					(
						#{
						#	"name":"hu_left_language_ui",
						#	"type":"expanded_image",
						#	"x":15,
						#	"y":10,
						#	"image":ROOT_PATH+"hu_lang_over.sub",
						#	"horizontal_align":"left",
						#},
						#{
						#	"name":"hu_right_language_ui",
						#	"type":"expanded_image",
						#	"x":41+15,
						#	"y":10,
						#	"image":ROOT_PATH+"hu_lang_over.sub",
						#	"horizontal_align":"right",
						#},
						#{
						#	"name":"hu_center_language_ui",
						#	"type":"expanded_image",
						#	"x":0,
						#	"y":18,
						#	"image":ROOT_PATH+"hu_lang_normal.sub",
						#	"horizontal_align":"center",
						#},
						#{
						#	"name":"pl_left_language_ui",
						#	"type":"expanded_image",
						#	"x":15,
						#	"y":10,
						#	"image":ROOT_PATH+"pl_lang_over.sub",
						#	"horizontal_align":"left",
						#},
						#{
						#	"name":"pl_right_language_ui",
						#	"type":"expanded_image",
						#	"x":41+15,
						#	"y":10,
						#	"image":ROOT_PATH+"pl_lang_over.sub",
						#	"horizontal_align":"right",
						#},
						#{
						#	"name":"pl_center_language_ui",
						#	"type":"expanded_image",
						#	"x":0,
						#	"y":18,
						#	"image":ROOT_PATH+"pl_lang_normal.sub",
						#	"horizontal_align":"center",
						#},
						# {
							# "name":"de_left_language_ui",
							# "type":"expanded_image",
							# "x":15,
							# "y":10,
							# "image":ROOT_PATH+"de_lang_over.sub",
							# "horizontal_align":"left",
						# },
						# {
							# "name":"de_right_language_ui",
							# "type":"expanded_image",
							# "x":41+15,
							# "y":10,
							# "image":ROOT_PATH+"de_lang_over.sub",
							# "horizontal_align":"right",
						# },
						# {
							# "name":"de_center_language_ui",
							# "type":"expanded_image",
							# "x":0,
							# "y":18,
							# "image":ROOT_PATH+"de_lang_normal.sub",
							# "horizontal_align":"center",
						# },
						{
							"name":"en_left_language_ui",
							"type":"expanded_image",
							"x":15,
							"y":10,
							"image":ROOT_PATH+"en_lang_over.sub",
							"horizontal_align":"left",
						},
						{
							"name":"en_right_language_ui",
							"type":"expanded_image",
							"x":41+15,
							"y":10,
							"image":ROOT_PATH+"en_lang_over.sub",
							"horizontal_align":"right",
						},
						{
							"name":"en_center_language_ui",
							"type":"expanded_image",
							"x":0,
							"y":18,
							"image":ROOT_PATH+"en_lang_normal.sub",
							"horizontal_align":"center",
						},
						# {
							# "name":"it_left_language_ui",
							# "type":"expanded_image",
							# "x":15,
							# "y":10,
							# "image":ROOT_PATH+"it_lang_over.sub",
							# "horizontal_align":"left",
						# },
						# {
							# "name":"it_right_language_ui",
							# "type":"expanded_image",
							# "x":41+15,
							# "y":10,
							# "image":ROOT_PATH+"it_lang_over.sub",
							# "horizontal_align":"right",
						# },
						# {
							# "name":"it_center_language_ui",
							# "type":"expanded_image",
							# "x":0,
							# "y":18,
							# "image":ROOT_PATH+"it_lang_normal.sub",
							# "horizontal_align":"center",
						# },
						# {
							# "name":"pt_left_language_ui",
							# "type":"expanded_image",
							# "x":15,
							# "y":10,
							# "image":ROOT_PATH+"pt_lang_over.sub",
							# "horizontal_align":"left",
						# },
						# {
							# "name":"pt_right_language_ui",
							# "type":"expanded_image",
							# "x":41+15,
							# "y":10,
							# "image":ROOT_PATH+"pt_lang_over.sub",
							# "horizontal_align":"right",
						# },
						# {
							# "name":"pt_center_language_ui",
							# "type":"expanded_image",
							# "x":0,
							# "y":18,
							# "image":ROOT_PATH+"pt_lang_normal.sub",
							# "horizontal_align":"center",
						# },
						{
							"name":"ro_left_language_ui",
							"type":"expanded_image",
							"x":15,
							"y":10,
							"image":ROOT_PATH+"ro_lang_over.sub",
							"horizontal_align":"left",
						},
						{
							"name":"ro_right_language_ui",
							"type":"expanded_image",
							"x":41+15,
							"y":10,
							"image":ROOT_PATH+"ro_lang_over.sub",
							"horizontal_align":"right",
						},
						{
							"name":"ro_center_language_ui",
							"type":"expanded_image",
							"x":0,
							"y":18,
							"image":ROOT_PATH+"ro_lang_normal.sub",
							"horizontal_align":"center",
						},
						# {
							# "name":"tr_left_language_ui",
							# "type":"expanded_image",
							# "x":15,
							# "y":10,
							# "image":ROOT_PATH+"tr_lang_over.sub",
							# "horizontal_align":"left",
						# },
						# {
							# "name":"tr_right_language_ui",
							# "type":"expanded_image",
							# "x":41+15,
							# "y":10,
							# "image":ROOT_PATH+"tr_lang_over.sub",
							# "horizontal_align":"right",
						# },
						# {
							# "name":"tr_center_language_ui",
							# "type":"expanded_image",
							# "x":0,
							# "y":18,
							# "image":ROOT_PATH+"tr_lang_normal.sub",
							# "horizontal_align":"center",
						# },
						{
							"name":"ArrowLeftButtonUI",
							"type":"button",
							"x":-80,
							"y":26,
							"default_image":ROOT_PATH+"left_arrow_normal.sub",
							"over_image":ROOT_PATH+"left_arrow_over.sub",
							"down_image":ROOT_PATH+"left_arrow_down.sub",
							"disable_image":ROOT_PATH+"left_arrow_down.sub",
							"horizontal_align":"center",
						},
						{
							"name":"ArrowRightButtonUI",
							"type":"button",
							"x":80,
							"y":26,
							"default_image":ROOT_PATH+"right_arrow_normal.sub",
							"over_image":ROOT_PATH+"right_arrow_over.sub",
							"down_image":ROOT_PATH+"right_arrow_down.sub",
							"disable_image":ROOT_PATH+"right_arrow_down.sub",
							"horizontal_align":"center",
						},
						{
							"name":"ConfirmButtonUI",
							"type":"button",
							"x":0,
							"y":33,
							"default_image":ROOT_PATH+"confirm_button_normal.sub",
							"over_image":ROOT_PATH+"confirm_button_down.sub",
							"down_image":ROOT_PATH+"confirm_button_over.sub",
							"disable_image":ROOT_PATH+"confirm_button_down.sub",
							"text":uiscriptlocale.LOGINWINDOW_CONFIRM,
							"horizontal_align":"center",
							"vertical_align":"bottom",
						},
					),
				},
			),
		},
		{
			"name":"LogoUI",
			"type":"ani_image",
			"x":(SCREEN_WIDTH / 2)-310,
			"y":(SCREEN_HEIGHT / 2)-176-250,
			"delay": 2,
			"images" : (
				IMG_PATHLOGO + "logo00000.dds",
				IMG_PATHLOGO + "logo00001.dds",
				IMG_PATHLOGO + "logo00002.dds",
				IMG_PATHLOGO + "logo00003.dds",
				IMG_PATHLOGO + "logo00004.dds",
				IMG_PATHLOGO + "logo00005.dds",
				IMG_PATHLOGO + "logo00006.dds",
				IMG_PATHLOGO + "logo00007.dds",
				IMG_PATHLOGO + "logo00008.dds",
				IMG_PATHLOGO + "logo00009.dds",
				IMG_PATHLOGO + "logo00010.dds",
				IMG_PATHLOGO + "logo00011.dds",
				IMG_PATHLOGO + "logo00012.dds",
				IMG_PATHLOGO + "logo00013.dds",
				IMG_PATHLOGO + "logo00014.dds",
				IMG_PATHLOGO + "logo00015.dds",
				IMG_PATHLOGO + "logo00016.dds",
				IMG_PATHLOGO + "logo00017.dds",
				IMG_PATHLOGO + "logo00018.dds",
				IMG_PATHLOGO + "logo00019.dds",
				IMG_PATHLOGO + "logo00020.dds",
				IMG_PATHLOGO + "logo00021.dds",
				IMG_PATHLOGO + "logo00022.dds",
				IMG_PATHLOGO + "logo00023.dds",
				IMG_PATHLOGO + "logo00024.dds",
				IMG_PATHLOGO + "logo00025.dds",
				IMG_PATHLOGO + "logo00026.dds",
				IMG_PATHLOGO + "logo00027.dds",
				IMG_PATHLOGO + "logo00028.dds",
				IMG_PATHLOGO + "logo00029.dds",
				IMG_PATHLOGO + "logo00030.dds",
				IMG_PATHLOGO + "logo00031.dds",
				IMG_PATHLOGO + "logo00032.dds",
				IMG_PATHLOGO + "logo00033.dds",
				IMG_PATHLOGO + "logo00034.dds",
				IMG_PATHLOGO + "logo00035.dds",
				IMG_PATHLOGO + "logo00036.dds",
				IMG_PATHLOGO + "logo00037.dds",
				IMG_PATHLOGO + "logo00038.dds",
				IMG_PATHLOGO + "logo00039.dds",
				IMG_PATHLOGO + "logo00040.dds",
				IMG_PATHLOGO + "logo00041.dds",
				IMG_PATHLOGO + "logo00042.dds",
				IMG_PATHLOGO + "logo00043.dds",
				IMG_PATHLOGO + "logo00044.dds",
				IMG_PATHLOGO + "logo00045.dds",
				IMG_PATHLOGO + "logo00046.dds",
				IMG_PATHLOGO + "logo00047.dds",
				IMG_PATHLOGO + "logo00048.dds",
				IMG_PATHLOGO + "logo00049.dds",
				IMG_PATHLOGO + "logo00050.dds",
				IMG_PATHLOGO + "logo00051.dds",
				IMG_PATHLOGO + "logo00052.dds",
				IMG_PATHLOGO + "logo00053.dds",
				IMG_PATHLOGO + "logo00054.dds",
				IMG_PATHLOGO + "logo00055.dds",
				IMG_PATHLOGO + "logo00056.dds",
				IMG_PATHLOGO + "logo00057.dds",
				IMG_PATHLOGO + "logo00058.dds",
				IMG_PATHLOGO + "logo00059.dds",
				IMG_PATHLOGO + "logo00060.dds",
				IMG_PATHLOGO + "logo00061.dds",
				IMG_PATHLOGO + "logo00062.dds",
				IMG_PATHLOGO + "logo00063.dds",
				IMG_PATHLOGO + "logo00064.dds",
				IMG_PATHLOGO + "logo00065.dds",
				IMG_PATHLOGO + "logo00066.dds",
				IMG_PATHLOGO + "logo00067.dds",
				IMG_PATHLOGO + "logo00068.dds",
				IMG_PATHLOGO + "logo00069.dds",
				IMG_PATHLOGO + "logo00070.dds",
				IMG_PATHLOGO + "logo00071.dds",
				IMG_PATHLOGO + "logo00072.dds",
				IMG_PATHLOGO + "logo00073.dds",
				IMG_PATHLOGO + "logo00074.dds",
				IMG_PATHLOGO + "logo00075.dds",
				IMG_PATHLOGO + "logo00076.dds",
				IMG_PATHLOGO + "logo00077.dds",
				IMG_PATHLOGO + "logo00078.dds",
				IMG_PATHLOGO + "logo00079.dds",
				IMG_PATHLOGO + "logo00080.dds",
				IMG_PATHLOGO + "logo00081.dds",
				IMG_PATHLOGO + "logo00082.dds",
				IMG_PATHLOGO + "logo00083.dds",
				IMG_PATHLOGO + "logo00084.dds",
				IMG_PATHLOGO + "logo00085.dds",
				IMG_PATHLOGO + "logo00086.dds",
				IMG_PATHLOGO + "logo00087.dds",
				IMG_PATHLOGO + "logo00088.dds",
				IMG_PATHLOGO + "logo00089.dds",
				IMG_PATHLOGO + "logo00090.dds",
				IMG_PATHLOGO + "logo00091.dds",
				IMG_PATHLOGO + "logo00092.dds",
				IMG_PATHLOGO + "logo00093.dds",
				IMG_PATHLOGO + "logo00094.dds",
				IMG_PATHLOGO + "logo00095.dds",
			),
		},
	),
}
