import localeinfo

window = {
	"name" : "ChangeChannelWindow",
	"style" : ("movable", "float"),
	"x" : (SCREEN_WIDTH - 190) / 2,
	"y" : (SCREEN_HEIGHT - 250) / 2,
	"width" : 190,
	"height" : 250,
	"children" :
	(
		{
			"name" : "MoveChannelBoard",
			"type" : "board",
			"style" : ("attach",),
			"x" : 0,
			"y" : 0,
			"width" : 190,
			"height" : 250,
			"children" :
			(
				{
					"name" : "title",
					"type" : "titlebar",
					"style" : ("attach",),
					"x" : 6,
					"y" : 7,
					"width" : 190 - 13,
					"children" :
					(
						{
							"name" : "TitleName",
							"type" : "text",
							"x" : 0,
							"y" : -2,
							"text": localeinfo.UI_CHANNEL_CHOOSE,
							"all_align":"center"
						},
					),
				},
				{
					"name" : "BlackBoard",
					"type" : "thinboard_circle",
					"x" : 13,
					"y" : 36,
					"width" : 190 - 26,
					"height" : 250 - 75,
					"children" :
					(
						{
							"name" : "btn_channel0",
							"type" : "button",
							"x" : 8,
							"y" : 6,
							"text" : "",
							"default_image" : "d:/ymir work/ui/game/myshop_deco/select_btn_01.sub",
							"over_image" : "d:/ymir work/ui/game/myshop_deco/select_btn_02.sub",
							"down_image" : "d:/ymir work/ui/game/myshop_deco/select_btn_03.sub",
						},
						{
							"name" : "btn_channel1",
							"type" : "button",
							"x" : 8,
							"y" : 6 + 28,
							"text" : "",
							"default_image" : "d:/ymir work/ui/game/myshop_deco/select_btn_01.sub",
							"over_image" : "d:/ymir work/ui/game/myshop_deco/select_btn_02.sub",
							"down_image" : "d:/ymir work/ui/game/myshop_deco/select_btn_03.sub",
						},
						{
							"name" : "btn_channel2",
							"type" : "button",
							"x" : 8,
							"y" : 6 + (28 * 2),
							"text" : "",
							"default_image" : "d:/ymir work/ui/game/myshop_deco/select_btn_01.sub",
							"over_image" : "d:/ymir work/ui/game/myshop_deco/select_btn_02.sub",
							"down_image" : "d:/ymir work/ui/game/myshop_deco/select_btn_03.sub",
						},
						{
							"name" : "btn_channel3",
							"type" : "button",
							"x" : 8,
							"y" : 6 + (28 * 3),
							"text" : "",
							"default_image" : "d:/ymir work/ui/game/myshop_deco/select_btn_01.sub",
							"over_image" : "d:/ymir work/ui/game/myshop_deco/select_btn_02.sub",
							"down_image" : "d:/ymir work/ui/game/myshop_deco/select_btn_03.sub",
						},
						# {
							# "name" : "btn_channel4",
							# "type" : "button",
							# "x" : 8,
							# "y" : 6 + (28 * 4),
							# "text" : "",
							# "default_image" : "d:/ymir work/ui/game/myshop_deco/select_btn_01.sub",
							# "over_image" : "d:/ymir work/ui/game/myshop_deco/select_btn_02.sub",
							# "down_image" : "d:/ymir work/ui/game/myshop_deco/select_btn_03.sub",
						# },
						# {
							# "name" : "btn_channel5",
							# "type" : "button",
							# "x" : 8,
							# "y" : 6 + (28 * 5),
							# "text" : "",
							# "default_image" : "d:/ymir work/ui/game/myshop_deco/select_btn_01.sub",
							# "over_image" : "d:/ymir work/ui/game/myshop_deco/select_btn_02.sub",
							# "down_image" : "d:/ymir work/ui/game/myshop_deco/select_btn_03.sub",
						# },
					),
				},
				{
					"name" : "btn_accept",
					"type" : "button",
					"x" : (190 / 2) - 67,
					"y" : 250 - 31,
					"text" : localeinfo.UI_CHANNEL_GO,
					"default_image" : "d:/ymir work/ui/public/middle_button_01.sub",
					"over_image" : "d:/ymir work/ui/public/middle_button_02.sub",
					"down_image" : "d:/ymir work/ui/public/middle_button_03.sub",
				},
				{
					"name" : "btn_close",
					"type" : "button",
					"x" : (190 / 2) + 6,
					"y" : 250 - 31,
					"text" : localeinfo.UI_CHANNEL_CLOSE,
					"default_image" : "d:/ymir work/ui/public/middle_button_01.sub",
					"over_image" : "d:/ymir work/ui/public/middle_button_02.sub",
					"down_image" : "d:/ymir work/ui/public/middle_button_03.sub",
				},
			),
		},
	),
}
