import uiscriptlocale

window = {
	"name" : "QuestionDropDialog",
	"style" : ("movable", "float",),
	"x" : SCREEN_WIDTH/2 - 125,
	"y" : SCREEN_HEIGHT/2 - 52,
	"width" : 260,
	"height" : 240,
	"children" :
	(
		{
			"name" : "board",
			"type" : "board",
			"x" : 0,
			"y" : 0,
			"width" : 260,
			"height" : 150,
			"children" :
			(
				{
					"name" : "thinboard",
					"type" : "thinboard",
					"x" : 4,
					"y" : 4,
					"width" : 260 - 8,
					"height" : 140,
				},
				{
					"name" : "message",
					"type" : "text",
					"x" : 0,
					"y" : 25,
					"horizontal_align" : "center",
					"text" : uiscriptlocale.MESSAGE,
					"text_horizontal_align" : "center",
					"text_vertical_align" : "center",
				},
				{
					"name" : "ItemSlot",
					"type" : "slot",
					"x" : 25,
					"y" : 45,
					"width" : 32,
					"height" : 98,
					"image" : "d:/ymir work/ui/public/Slot_Base.sub",
					"slot" : (
						{"index":0, "x":0, "y":0, "width":32, "height":32},
						{"index":1, "x":0, "y":33, "width":32, "height":32},
						{"index":2, "x":0, "y":66, "width":32, "height":32},
					),
				},
				{
					"name" : "button_holder",
					"type" : "thinboard_circle",
					"x" : 20,
					"y" : 45,
					"width" : 160,
					"height" : 70-5,
					"horizontal_align" : "center",
					"children" :
					(
						{
							"name" : "accept",
							"type" : "button",
							"x" : 10,
							"y" : 8,
							# "horizontal_align" : "center",
							# "text" : uiscriptlocale.OPTION_DROP,
							"default_image" : "d:/ymir work/ui/public/acceptbutton00.sub",
							"over_image" : "d:/ymir work/ui/public/acceptbutton01.sub",
							"down_image" : "d:/ymir work/ui/public/acceptbutton02.sub",
						},
						{
							"name" : "destroy",
							"type" : "button",
							"x" : 10,
							"y" : 8 + 30,
							# "horizontal_align" : "center",
							# "text" : uiscriptlocale.DESTROY,
							"default_image" : "d:/ymir work/ui/pattern/delete_button_0.tga",
							"over_image" : "d:/ymir work/ui/pattern/delete_button_1.tga",
							"down_image" : "d:/ymir work/ui/pattern/delete_button_2.tga",
						},
						{
							"name" : "exchange_element",
							"type" : "button",
							"x" : 35,
							"y" : 8 + 30,
							"horizontal_align" : "center",
							# "text" : uiscriptlocale.OPTION_CHANGE,
							"default_image" : "d:/ymir work/ui/pattern/craft_button_0.tga",
							"over_image" : "d:/ymir work/ui/pattern/craft_button_1.tga",
							"down_image" : "d:/ymir work/ui/pattern/craft_button_2.tga",
						},
						{
							"name" : "cancel",
							"type" : "button",
							"x" : 35,
							"y" : 8,
							"horizontal_align" : "center",
							# "text" : uiscriptlocale.CANCEL,
							"default_image" : "d:/ymir work/ui/public/canclebutton00.sub",
							"over_image" : "d:/ymir work/ui/public/canclebutton01.sub",
							"down_image" : "d:/ymir work/ui/public/canclebutton02.sub",
						},
					),
				},
			),
		},
	),
}
